### ISSUE TITLE
Only one bot connects

### ISSUE THREAD

**Issue by malafk** [Eoghanmc22/rust-mc-bot#4]
./rust-mc-bot redacted 10
cpus: 12
TCP(redacted:25565)
TCP(redacted:25565)
TCP(redacted:25565)
TCP(redacted:25565)
TCP(redacted:25565)
TCP(redacted:25565)
TCP(redacted:25565)
TCP(redacted:25565)
TCP(redacted:25565)
TCP(redacted:25565)
bot "Bot_0" joined
thread '<unnamed>' panicked at 'Could not connect to the server: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }', src/main.rs:279:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'Could not connect to the server: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }Could not connect to the server: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }', ', src/main.rssrc/main.rs::279279::68
68
thread 'thread 'thread '<unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at 'Could not connect to the server: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }Could not connect to the server: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }Could not connect to the server: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }', ', ', src/main.rssrc/main.rssrc/main.rsthread ':::279<unnamed>279279:' panicked at '68Could not connect to the server: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }::thread '
', 6868<unnamed>src/main.rs

' panicked at ':Could not connect to the server: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }279', :src/main.rs68:
279:68
thread '<unnamed>' panicked at 'Could not connect to the server: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }', src/main.rs:279:68

**Comment by malafk** [comment]
Fixed by restarting machine
